version: '3.5'
networks: 
    appnet:
        driver: bridge
services:
    db: 
        image: mysql:8.0.22
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: Rootuser012%
            MYSQL_DATABASE: InfiniteScroll_development
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: Mysql012%
        networks: 
            - appnet
        volumes: 
          - /var/lib/mysql
    app: 
        build: .
        networks: 
          - appnet
        volumes: 
          - ".:/app"
        ports: 
          - "3000:3000"
        depends_on:
          - db
        links:
          - db
        environment:
          DB_USER: mysqluser
          DB_NAME: InfiniteScroll_development
          DB_PASSWORD: Mysql012%
          DB_HOST: db